import React, { useMemo, useState, useEffect } from "react";import { useParams } from "react-router-dom";import PackageCard from "./PackageCard";import "./Cards.css";import RentaVehiculos from "./RentaVehiculos";import { useAutoRefreshPackages } from "../hooks/useAutoRefresh";

const slugToCategory = (slug) => {const map = {"hoteles": "Hoteles en la Riviera Maya","hoteles-nacionales": "Hoteles Nacionales","paquetes-nacionales": "Nuestros paquetes nacionales","pasadias": "Nuestros pasadías","paquetes-internacionales": "Nuestros paquetes internacionales","viajes-europa": "Nuestros viajes a Europa","renta-vehiculos": "Renta de vehículos"};return map[slug] || null;};

const categoryTitle = (slug) => {const map = {"hoteles": "Hoteles en la Riviera Maya","hoteles-nacionales": "Hoteles Nacionales","paquetes-nacionales": "Nuestros paquetes nacionales","pasadias": "Nuestros pasadías","paquetes-internacionales": "Nuestros paquetes internacionales","viajes-europa": "Nuestros viajes a Europa","renta-vehiculos": "Renta de vehículos"};return map[slug] || "Servicio";};

const slugToThemeClass = (slug) => {const map = {"hoteles": "theme-hoteles","hoteles-nacionales": "theme-nacionales","paquetes-nacionales": "theme-nacionales","pasadias": "theme-pasadias","paquetes-internacionales": "theme-internacionales","viajes-europa": "theme-europa","renta-vehiculos": "theme-renta-vehiculos"};return map[slug] || "";};

const ServiceDetail = () => {const { slug } = useParams();const category = slugToCategory(slug);const [month, setMonth] = useState("");const [popularOnly, setPopularOnly] = useState(false);const params = useMemo(() => { const p = {}; if (category) p.category = category; if (month) p.month = month; if (popularOnly) p.popular = "true"; return p; }, [category, month, popularOnly]);const { data: packages, loading, error, refetchNow } = useAutoRefreshPackages(params, 2000);const [lastPackages, setLastPackages] = useState([]);useEffect(() => { if (Array.isArray(packages)) { setLastPackages(prev => packages.length ? packages : prev); } }, [packages]);useEffect(() => { refetchNow(); }, [month, popularOnly, category, refetchNow]);

const headerTitle = useMemo(() => categoryTitle(slug), [slug]);const displayedPackages = loading ? lastPackages : (Array.isArray(packages) ? packages : []);

if (slug === 'renta-vehiculos') {return (<RentaVehiculos />);} 

if (!category) {return (<div className={`cards ${slugToThemeClass(slug)}`}><div className='packages-header'><h1 className='service-title'>{headerTitle}</h1><p className='service-subtitle'>La categoría solicitada no existe.</p></div></div>);} 

return (<div className={`cards ${slugToThemeClass(slug)}`}><div className='packages-header'><h1 className='service-title'>{headerTitle}</h1><p className='service-subtitle'>Explora los paquetes disponibles en esta modalidad.</p></div>{error && <div className='status error'>{error}</div>}<div className='search-bar d-flex gap-2 align-items-center mb-3'><input type='month' className='form-control' value={month} onChange={(e) => setMonth(e.target.value)} /><button onClick={() => refetchNow()} className='btn btn-primary'>Buscar</button>{month && <button onClick={() => setMonth("")} className='btn btn-secondary'>Limpiar</button>}<div className='form-check ms-2'><input id='popularOnly' type='checkbox' className='form-check-input' checked={popularOnly} onChange={(e) => setPopularOnly(e.target.checked)} /><label htmlFor='popularOnly' className='form-check-label'>Solo populares</label></div></div>{/* Carga manejada por overlay global de transición */}{!loading && !error && displayedPackages.length === 0 && (<div className='status info'>No hay paquetes en la categoría "{headerTitle}".</div>)}<div className='cards__container'><div className='cards__wrapper'><ul className='cards__items packages-grid'>{displayedPackages.map((pkg) => (<li className='cards__item' key={pkg._id}><PackageCard pkg={pkg} plain showIncludes /></li>))}</ul></div></div></div>);};

export default ServiceDetail;